In [1]:
#Import the relevant Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [4]:
#load neccessary data
crime_2022 = pd.read_csv('tmpattplu_0.csv',low_memory=False)
crime_2021 =pd.read_csv('tmp7_f32p54 (4).csv',low_memory=False)
crime_2020 = pd.read_csv('script_113631134_20210423193017_combine (3).csv',low_memory=False)
crime_2019 = pd.read_csv('tmp9mkqyv6b (3).csv',low_memory=False)
crime_2018 = pd.read_csv('crime-incident-reports-2018 (3).csv',low_memory=False)
crime_2017 = pd.read_csv('crime-incident-reports-2017 (3).csv',low_memory=False)
crime_2016 = pd.read_csv('crime-incident-reports-2016 (2).csv',low_memory=False)
crime_2015 = pd.read_csv('crime-incident-reports-2015 (3).csv',low_memory=False)

In [5]:
crime_2022

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,S87066666,3301,NaN,VERBAL DISPUTE,B2,300,0,2022-04-07 19:30:00,2022,4,Thursday,19,NaN,THORNTON PLACE,0.000000,0.000000,"(0, 0)"
1,225520077,3115,NaN,INVESTIGATE PERSON,D14,786,0,2022-02-02 00:00:00,2022,2,Wednesday,0,NaN,WASHINGTON ST,42.343081,-71.141723,"(42.34308127134165, -71.14172267328729)"
2,223260108,3115,NaN,INVESTIGATE PERSON,D4,154,0,2022-11-22 09:35:00,2022,11,Tuesday,9,NaN,COLUMBUS AVE,42.342899,-71.078800,"(42.342898500827786, -71.07880000122785)"
3,222934485,3831,NaN,M/V - LEAVING SCENE - PROPERTY DAMAGE,B2,319,0,2022-05-14 20:50:00,2022,5,Saturday,20,NaN,BLUE HILL AVE,42.308038,-71.083592,"(42.30803768051951, -71.08359213073199)"
4,222924960,3301,NaN,VERBAL DISPUTE,C11,355,0,2022-04-09 16:30:00,2022,4,Saturday,16,NaN,GIBSON ST,42.297555,-71.059709,"(42.29755532959655, -71.05970910242573)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66899,122004001,3115,NaN,INVESTIGATE PERSON,E13,912,0,2022-01-19 09:30:00,2022,1,Wednesday,9,NaN,HEATH ST,42.325131,-71.099408,"(42.32513050637361, -71.09940814578592)"
66900,111077848,3115,NaN,INVESTIGATE PERSON,E5,691,0,2022-10-09 00:00:00,2022,10,Sunday,0,NaN,CENTRE ST,42.287094,-71.148221,"(42.28709355259107, -71.14822128377165)"
66901,168393102,1402,NaN,VANDALISM,C11,355,0,2022-11-23 19:00:00,2022,11,Wednesday,19,NaN,GIBSON ST,42.297555,-71.059709,"(42.29755532959655, -71.05970910242573)"
66902,149210376,3110,NaN,SERVICE TO OTHER AGENCY,B2,,0,2022-01-02 00:00:00,2022,1,Sunday,0,NaN,WASHINGTON ST & ROXBURY ST\nBOSTON MA 02119\n...,42.329600,-71.084620,"(42.32959998129787, -71.08462000476281)"
66903,022031068,3114,NaN,INVESTIGATE PROPERTY,C11,249,0,2022-05-02 08:00:00,2022,5,Monday,8,NaN,SAXTON ST,42.313591,-71.054324,"(42.31359091105722, -71.05432387045848)"

In [7]:
crime_2022.OFFENSE_DESCRIPTION.unique()

array(['VERBAL DISPUTE', 'INVESTIGATE PERSON',
       'M/V - LEAVING SCENE - PROPERTY DAMAGE', 'PROPERTY - FOUND',
       'MISSING PERSON - NOT REPORTED - LOCATED', 'FUGITIVE FROM JUSTICE',
       'HARASSMENT/ CRIMINAL HARASSMENT', 'PROPERTY - LOST/ MISSING',
       'FRAUD - CREDIT CARD / ATM FRAUD', 'LARCENY ALL OTHERS',
       'AUTO THEFT', 'ROBBERY', 'LANDLORD - TENANT',
       'WARRANT ARREST - BOSTON WARRANT (MUST BE SUPPLEMENTAL)',
       'DRUGS - POSSESSION/ SALE/ MANUFACTURING/ USE', 'ASSAULT - SIMPLE',
       'LARCENY THEFT FROM MV - NON-ACCESSORY', 'SICK ASSIST',
       'BURGLARY - RESIDENTIAL', 'SERVICE TO OTHER AGENCY',
       'ASSAULT - AGGRAVATED',
       'M/V ACCIDENT - INVOLVING PEDESTRIAN - NO INJURY',
       'M/V ACCIDENT - OTHER', 'LICENSE PREMISE VIOLATION',
       'VAL - OPERATING AFTER REV/SUSP.', 'VANDALISM',
       'FIREARM/WEAPON - FOUND OR CONFISCATED', 'INVESTIGATE PROPERTY',
       'DISTURBING THE PEACE/ DISORDERLY CONDUCT/ GATHERING CAUSING ANNOYANCE/ NOISY PAR',
       'LARCENY THEFT FROM BUILDING', 'LARCENY SHOPLIFTING',
       'VAL - OPERATING W/O AUTHORIZATION LAWFUL', 'TOWED MOTOR VEHICLE',
       'BREAKING AND ENTERING (B&E) MOTOR VEHICLE (NO PROPERTY STOLEN)',
       'M/V ACCIDENT - PERSONAL INJURY', 'BALLISTICS EVIDENCE/FOUND',
       'SICK/INJURED/MEDICAL - PERSON', 'M/V ACCIDENT - PROPERTY DAMAGE',
       'M/V PLATES - LOST', 'FRAUD - FALSE PRETENSE / SCHEME',
       'SICK ASSIST - DRUG RELATED ILLNESS', 'MISSING PERSON',
       'M/V ACCIDENT - INVOLVING PEDESTRIAN - INJURY',
       'THREATS TO DO BODILY HARM',
       'M/V ACCIDENT - INVOLVING BICYCLE - NO INJURY',
       'PROPERTY - ACCIDENTAL DAMAGE', 'VAL - VIOLATION OF AUTO LAW',
       'CHILD REQUIRING ASSISTANCE (FOMERLY CHINS)',
       'FIREARM/WEAPON - LOST', 'FORGERY / COUNTERFEITING',
       'DEATH INVESTIGATION', 'LARCENY THEFT OF MV PARTS & ACCESSORIES',
       'OPERATING UNDER THE INFLUENCE (OUI) ALCOHOL',
       'SICK/INJURED/MEDICAL - POLICE',
       'RECOVERED - MV RECOVERED IN BOSTON (STOLEN OUTSIDE BOSTON)',
       'WARRANT ARREST - OUTSIDE OF BOSTON WARRANT',
       'AUTO THEFT - MOTORCYCLE / SCOOTER', 'MISSING PERSON - LOCATED',
       'LARCENY THEFT OF BICYCLE', 'SUDDEN DEATH',
       'ANIMAL INCIDENTS (DOG BITES, LOST DOG, ETC)', 'FIRE REPORT',
       'M/V ACCIDENT - POLICE VEHICLE', 'AFFRAY', 'ARSON',
       'FIRE REPORT/ALARM - FALSE',
       'BREAKING AND ENTERING (B&E) MOTOR VEHICLE', 'FRAUD - WIRE',
       'M/V ACCIDENT - OTHER CITY VEHICLE', 'EXTORTION OR BLACKMAIL',
       'FRAUD - IMPERSONATION', 'TRESPASSING', 'EMBEZZLEMENT',
       'M/V - LEAVING SCENE - PERSONAL INJURY', 'SEARCH WARRANT',
       'STOLEN PROPERTY - BUYING / RECEIVING / POSSESSING',
       'BURGLARY - COMMERICAL', 'BOMB THREAT', 'AIRCRAFT INCIDENTS',
       'KIDNAPPING/CUSTODIAL KIDNAPPING/ ABDUCTION',
       'LARCENY PICK-POCKET', 'M/V ACCIDENT - INVOLVING BICYCLE - INJURY',
       'PROPERTY - LOST THEN LOCATED', 'NOISY PARTY/RADIO-NO ARREST',
       'HARBOR INCIDENT / VIOLATION', 'OTHER OFFENSE',
       'WEAPON VIOLATION - CARRY/ POSSESSING/ SALE/ TRAFFICKING/ OTHER',
       'AUTO THEFT - LEASED/RENTED VEHICLE',
       'DRUGS - POSSESSION OF DRUG PARAPHANALIA',
       'EXPLOSIVES - POSSESSION OR USE',
       'PROPERTY - STOLEN THEN RECOVERED', 'ANIMAL ABUSE', 'EVADING FARE',
       'MURDER, NON-NEGLIGENT MANSLAUGHTER', 'FRAUD - WELFARE',
       'INJURY BICYCLE NO M/V INVOLVED',
       'LIQUOR/ALCOHOL - DRINKING IN PUBLIC', 'INTIMIDATING WITNESS',
       'LARCENY PURSE SNATCH - NO FORCE', 'VIOLATION - CITY ORDINANCE',
       'SUICIDE / SUICIDE ATTEMPT',
       'RECOVERED - MV RECOVERED IN BOSTON (STOLEN IN BOSTON) MUST BE SUPPLEMENTAL',
       'DANGEROUS OR HAZARDOUS CONDITION',
       'MURDER, NON-NEGLIGIENT MANSLAUGHTER', 'PROSTITUTION - SOLICITING',
       'PRISONER - SUICIDE / SUICIDE ATTEMPT',
       'FIREARM/WEAPON - ACCIDENTAL INJURY / DEATH', 'GRAFFITI',
       'POSSESSION OF BURGLARIOUS TOOLS',
       'LARCENY THEFT FROM COIN-OP MACHINE', 'TRUANCY / RUNAWAY',
       'PRISONER ESCAPE / ESCAPE & RECAPTURE',
       'PROTECTIVE CUSTODY / SAFEKEEPING', 'LIQUOR LAW VIOLATION',
       'OPERATING UNDER THE INFLUENCE (OUI) DRUGS', 'PROSTITUTION',
       'DRUNKENNESS', 'EXPLOSIVES - TURNED IN OR FOUND',
       'MANSLAUGHTER - VEHICLE - NEGLIGENCE'], dtype=object)

In [10]:
import fuzzywuzzy as fuzzywuzzy
from fuzzywuzzy import process, fuzz

In [24]:
#Look at Violent crimes, Violent Crime
#In the FBI’s Uniform Crime Reporting (UCR) Program, violent crime is composed of four offenses: murder and nonnegligent manslaughter, forcible rape, robbery, and aggravated assault. Violent crimes are defined in the UCR Program as those offenses which involve force or threat of force.


string_to_match = 'murder'
min_ratio = 90
    # get a list of unique strings
strings = crime_2022.OFFENSE_DESCRIPTION.unique()

    # get the top 5 closest matches to our input string
matches = fuzzywuzzy.process.extract(string_to_match, strings, limit=5, scorer=fuzzywuzzy.fuzz.token_set_ratio)
# only get matches with a ratio >   
print(matches)

[('MURDER, NON-NEGLIGENT MANSLAUGHTER', 100), ('MURDER, NON-NEGLIGIENT MANSLAUGHTER', 100), ('ROBBERY', 46), ('FRAUD - WELFARE', 42), ('PROPERTY - FOUND', 40)]

In [27]:
string_to_match = 'robbery'
min_ratio = 90
    # get a list of unique strings
strings = crime_2022.OFFENSE_DESCRIPTION.unique()

    # get the top 5 closest matches to our input string
matches = fuzzywuzzy.process.extract(string_to_match, strings, limit=5, scorer=fuzzywuzzy.fuzz.token_set_ratio)
# only get matches with a ratio >   
print(matches)

[('ROBBERY', 100), ('PROPERTY - FOUND', 48), ('INVESTIGATE PROPERTY', 37), ('PROPERTY - LOST/ MISSING', 36), ('FORGERY / COUNTERFEITING', 34)]

In [28]:
string_to_match = 'assault'
min_ratio = 90
    # get a list of unique strings
strings = crime_2022.OFFENSE_DESCRIPTION.unique()

    # get the top 5 closest matches to our input string
matches = fuzzywuzzy.process.extract(string_to_match, strings, limit=5, scorer=fuzzywuzzy.fuzz.token_set_ratio)
# only get matches with a ratio >   
print(matches)

[('ASSAULT - SIMPLE', 100), ('ASSAULT - AGGRAVATED', 100), ('SICK ASSIST', 44), ('ANIMAL ABUSE', 42), ('VANDALISM', 38)]

In [29]:
string_to_match = 'drugs'
min_ratio = 90
    # get a list of unique strings
strings = crime_2022.OFFENSE_DESCRIPTION.unique()

    # get the top 5 closest matches to our input string
matches = fuzzywuzzy.process.extract(string_to_match, strings, limit=5, scorer=fuzzywuzzy.fuzz.token_set_ratio)
# only get matches with a ratio >   
print(matches)

[('DRUGS - POSSESSION/ SALE/ MANUFACTURING/ USE', 100), ('DRUGS - POSSESSION OF DRUG PARAPHANALIA', 100), ('OPERATING UNDER THE INFLUENCE (OUI) DRUGS', 100), ('DRUNKENNESS', 50), ('ARSON', 40)]

In [63]:
violent_crime_2022 = crime_2022.loc[(crime_2022['OFFENSE_DESCRIPTION'] == 'MURDER, NON-NEGLIGENT MANSLAUGHTER') |
                                (crime_2022['OFFENSE_DESCRIPTION'] ==     'MURDER, NON-NEGLIGIENT MANSLAUGHTER') |
                                (crime_2022['OFFENSE_DESCRIPTION'] == 'ROBBERY')|
                                (crime_2022['OFFENSE_DESCRIPTION'] ==  'ASSAULT - AGGRAVATED')]
                             
                                                  
violent_crime_2022

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
17,222201559,301,NaN,ROBBERY,D4,,0,2022-03-05 13:00:00,2022,3,Saturday,13,NaN,ALBANY ST,42.333184,-71.073939,"(42.333184490911954, -71.07393881002383)"
31,222091588,423,NaN,ASSAULT - AGGRAVATED,C11,370,0,2022-11-27 00:00:00,2022,11,Sunday,0,NaN,WILLIAM T MORRISSEY BLVD,42.294093,-71.047281,"(42.29409261717923, -71.04728058843737)"
83,222091500,423,NaN,ASSAULT - AGGRAVATED,B3,,1,2022-11-26 17:25:00,2022,11,Saturday,17,NaN,WESTMORE RD,42.284692,-71.096215,"(42.284691637688994, -71.09621547481711)"
114,222091451,301,NaN,ROBBERY,C11,,0,2022-11-25 18:30:00,2022,11,Friday,18,NaN,GIBSON ST,42.297555,-71.059709,"(42.29755532959655, -71.05970910242573)"
139,222091415,423,NaN,ASSAULT - AGGRAVATED,E18,,0,2022-11-26 11:52:00,2022,11,Saturday,11,NaN,HYDE PARK AVE,42.279306,-71.119098,"(42.27930647658092, -71.11909810425672)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66720,222034143,423,NaN,ASSAULT - AGGRAVATED,D14,,0,2022-05-13 15:48:00,2022,5,Friday,15,NaN,BRIGHTON AVE,42.353298,-71.135049,"(42.35329807569462, -71.1350494761337)"
66797,222034042,423,NaN,ASSAULT - AGGRAVATED,C11,355,0,2022-05-12 17:40:00,2022,5,Thursday,17,NaN,GIBSON ST,42.297555,-71.059709,"(42.29755532959655, -71.05970910242573)"
66843,222033981,423,NaN,ASSAULT - AGGRAVATED,B2,,0,2022-05-13 04:35:00,2022,5,Friday,4,NaN,CRISPUS ATTUCKS PL,42.324539,-71.088218,"(42.324538596114216, -71.08821844264244)"
66862,222033953,301,NaN,ROBBERY,A1,,0,2022-05-12 23:45:00,2022,5,Thursday,23,NaN,BOYLSTON ST & ARLINGTON ST\nBOSTON MA 02116\n...,42.351870,-71.070690,"(42.351869957689175, -71.07069005295821)"
66891,222088987,423,NaN,ASSAULT - AGGRAVATED,C11,355,0,2022-11-16 16:40:00,2022,11,Wednesday,16,NaN,GIBSON ST,42.297555,-71.059709,"(42.29755532959655, -71.05970910242573)"

In [67]:
string_to_match1 = 'robbery'
string_to_match2 = 'murder'
string_to_match3 = 'assault'
min_ratio = 90
    # get a list of unique strings
strings = crime_2021.OFFENSE_DESCRIPTION.unique()

    # get the top 5 closest matches to our input string
matches1 = fuzzywuzzy.process.extract(string_to_match1, strings, limit=5, scorer=fuzzywuzzy.fuzz.token_set_ratio)
matches2 = fuzzywuzzy.process.extract(string_to_match2, strings, limit=5, scorer=fuzzywuzzy.fuzz.token_set_ratio)
matches3 = fuzzywuzzy.process.extract(string_to_match, strings, limit=5, scorer=fuzzywuzzy.fuzz.token_set_ratio)
# only get matches with a ratio >   
dfmatches1, matches2, matches3)

[('ROBBERY', 100), ('PROPERTY - FOUND', 48), ('INVESTIGATE PROPERTY', 37), ('PROPERTY - LOST/ MISSING', 36), ('FORGERY / COUNTERFEITING', 34)] [('MURDER, NON-NEGLIGIENT MANSLAUGHTER', 100), ('ROBBERY', 46), ('FRAUD - WELFARE', 42), ('PROPERTY - FOUND', 40), ('FRAUD - WIRE', 38)] [('ROBBERY', 100), ('PROPERTY - FOUND', 48), ('INVESTIGATE PROPERTY', 37), ('PROPERTY - LOST/ MISSING', 36), ('FORGERY / COUNTERFEITING', 34)]

In [57]:
violent_crime_2021= crime_2021.loc[(crime_2021['OFFENSE_DESCRIPTION'] == 'MURDER, NON-NEGLIGENT MANSLAUGHTER') |
                             (crime_2021['OFFENSE_DESCRIPTION'] == 'ROBBERY')|
                             (crime_2021['OFFENSE_DESCRIPTION'] ==  'ASSAULT - AGGRAVATED')]
                             
                                                  
violent_crime_2021

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
95,212095529,423,NaN,ASSAULT - AGGRAVATED,B2,,0,2021-12-31 22:47:00,2021,12,Friday,22,NaN,WARREN ST,42.316966,-71.082541,"(42.31696649906326, -71.08254057648374)"
136,212095467,301,NaN,ROBBERY,C11,,0,2021-12-31 18:33:00,2021,12,Friday,18,NaN,ASHMONT ST & DORCHESTER AVE\nDORCHESTER MA 02...,42.285752,-71.064309,"(42.28575202058727, -71.06430902906185)"
152,212095448,301,NaN,ROBBERY,C11,,0,2021-12-31 16:58:00,2021,12,Friday,16,NaN,DORCHESTER AVE,42.278399,-71.066363,"(42.27839920113053, -71.06636305093119)"
158,212095441,423,NaN,ASSAULT - AGGRAVATED,B3,,0,2021-12-31 15:27:00,2021,12,Friday,15,NaN,GILMER ST,42.282811,-71.097223,"(42.28281073542675, -71.09722321342178)"
209,212095368,301,NaN,ROBBERY,D4,,0,2021-12-31 07:40:00,2021,12,Friday,7,NaN,HARRISON AVE,42.344934,-71.063664,"(42.3449342783627, -71.06366373548889)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71324,210046064,423,NaN,ASSAULT - AGGRAVATED,A7,24,0,2021-02-01 16:56:00,2021,2,Monday,16,NaN,MERIDIAN ST,42.379965,-71.039233,"(42.37996488667934, -71.03923314410417)"
71370,212090399,423,NaN,ASSAULT - AGGRAVATED,B2,,0,2021-12-10 15:44:00,2021,12,Friday,15,NaN,WARREN ST,42.316966,-71.082541,"(42.31696649906326, -71.08254057648374)"
71657,212089785,423,NaN,ASSAULT - AGGRAVATED,E5,,0,2021-12-08 14:05:00,2021,12,Wednesday,14,NaN,RIVERMOOR STREET,0.000000,0.000000,"(0, 0)"
71659,212089783,423,NaN,ASSAULT - AGGRAVATED,A7,,0,2021-12-08 14:09:00,2021,12,Wednesday,14,NaN,BENNINGTON ST,42.375470,-71.037302,"(42.37546983016921, -71.03730221130624)"
71681,212092237,301,NaN,ROBBERY,A7,,0,2021-12-17 10:01:00,2021,12,Friday,10,NaN,WEBSTER ST,42.366900,-71.037419,"(42.36690003141896, -71.03741911710055)"

In [58]:
violent_crime_2020= crime_2020.loc[(crime_2020['OFFENSE_DESCRIPTION'] == 'MURDER, NON-NEGLIGENT MANSLAUGHTER') |
                             (crime_2020['OFFENSE_DESCRIPTION'] == 'ROBBERY')|
                             (crime_2020['OFFENSE_DESCRIPTION'] ==  'ASSAULT - AGGRAVATED')]
                             
                                                  
violent_crime_2020

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
122,202074423,423,NaN,ASSAULT - AGGRAVATED,C6,,0,2020-10-09 16:37:00,2020,10,Friday,16,NaN,GAVIN WAY,0.000000,0.000000,"(0, 0)"
178,202069145,301,NaN,ROBBERY,B2,320,0,2020-09-21 14:50:00,2020,9,Monday,14,NaN,BLUE HILL AVE,0.000000,0.000000,"(0, 0)"
322,212001699,423,NaN,ASSAULT - AGGRAVATED,E5,563,0,2020-12-13 17:51:00,2020,12,Sunday,17,NaN,STELLMAN RD,42.289199,-71.123092,"(42.289199015513, -71.123091950958)"
374,212000805,301,NaN,ROBBERY,E18,355,0,2020-11-28 00:00:00,2020,11,Saturday,0,NaN,BRADLEE ST,42.297555,-71.059709,"(42.2975553295965, -71.0597091024257)"
383,212000722,423,NaN,ASSAULT - AGGRAVATED,C11,355,0,2020-12-26 12:15:00,2020,12,Saturday,12,NaN,WASHINGTON ST,42.297555,-71.059709,"(42.2975553295965, -71.0597091024257)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70769,202000022,301,NaN,ROBBERY,D14,,0,2020-01-01 01:40:00,2020,1,Wednesday,1,NaN,COMMONWEALTH AVE,42.350740,-71.130479,"(42.3507396316499, -71.1304790941051)"
70815,200293622,423,NaN,ASSAULT - AGGRAVATED,C11,365,0,2020-06-15 14:45:00,2020,6,Monday,14,NaN,KING ST,42.292731,-71.058861,"(42.2927312398048, -71.0588611599788)"
70820,200284533,301,NaN,ROBBERY,A1,520,0,2020-06-10 14:00:00,2020,6,Wednesday,14,NaN,WEST ST,42.256216,-71.124019,"(42.2562159204022, -71.1240194732902)"
70838,200204397,301,NaN,ROBBERY,D4,142,0,2020-06-23 12:45:00,2020,6,Tuesday,12,NaN,NEWBURY ST,42.348406,-71.086883,"(42.3484057624732, -71.0868833874023)"
70860,200063547,423,NaN,ASSAULT - AGGRAVATED,A7,26,0,2020-01-28 13:43:00,2020,1,Tuesday,13,NaN,BORDER ST,42.377876,-71.039952,"(42.3778757322659, -71.0399520843088)"

In [60]:
violent_crime_2019 = crime_2019.loc[(crime_2019['OFFENSE_DESCRIPTION'] == 'MURDER, NON-NEGLIGENT MANSLAUGHTER') |
                             (crime_2019['OFFENSE_DESCRIPTION'] == 'ROBBERY')|
                             (crime_2019['OFFENSE_DESCRIPTION'] ==  'ASSAULT - AGGRAVATED')]
                             
                                                  
violent_crime_2019

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
43,191101616,301,NaN,ROBBERY,E13,574,0,2019-12-17 13:35:00,2019,12,Tuesday,13,NaN,BROOKSIDE AVE,0.000000,0.000000,"(0, 0)"
219,192078655,301,NaN,ROBBERY,B3,467,0,2019-09-29 07:12:00,2019,9,Sunday,7,NaN,GILMER,42.282811,-71.097223,"(42.28281073542675, -71.09722321342178)"
299,192078763,301,NaN,ROBBERY,E13,302,0,2019-09-29 15:12:00,2019,9,Sunday,15,NaN,CENTRE ST,42.322798,-71.100331,"(42.322797825283104, -71.10033101200467)"
353,192078824,423,NaN,ASSAULT - AGGRAVATED,B2,280,0,2019-09-29 20:01:00,2019,9,Sunday,20,NaN,DUDLEY ST,42.328726,-71.083822,"(42.32872588572028, -71.08382216968015)"
366,192078845,423,NaN,ASSAULT - AGGRAVATED,D4,271,0,2019-09-29 21:52:00,2019,9,Sunday,21,NaN,HARRISON AVE,42.334018,-71.076381,"(42.33401828958511, -71.07638123930862)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86537,192075085,423,NaN,ASSAULT - AGGRAVATED,A1,98,0,2019-09-18 13:00:00,2019,9,Wednesday,13,NaN,WATER ST,42.357592,-71.057725,"(0, 0)"
86660,192077010,423,NaN,ASSAULT - AGGRAVATED,B3,,0,2019-09-20 16:10:00,2019,9,Friday,16,NaN,BLUE HILL AVE,42.275679,-71.093640,"(0, 0)"
86749,192076281,423,NaN,ASSAULT - AGGRAVATED,E13,572,0,2019-09-22 02:39:49,2019,9,Sunday,2,NaN,WALNUT AVE,42.312860,-71.095728,"(0, 0)"
86761,192076324,423,NaN,ASSAULT - AGGRAVATED,B2,298,0,2019-09-22 09:22:00,2019,9,Sunday,9,NaN,WALNUT AVE,42.323209,-71.084330,"(0, 0)"
87005,192077602,423,NaN,ASSAULT - AGGRAVATED,D14,769,0,2019-09-25 21:14:00,2019,9,Wednesday,21,NaN,LEICESTER ST,42.352911,-71.153077,"(0, 0)"

In [61]:
violent_crime_2018= crime_2018.loc[(crime_2018['OFFENSE_DESCRIPTION'] == 'MURDER, NON-NEGLIGENT MANSLAUGHTER') |
                             (crime_2018['OFFENSE_DESCRIPTION'] == 'ROBBERY')|
                             (crime_2018['OFFENSE_DESCRIPTION'] ==  'ASSAULT - AGGRAVATED')]
                             
                                                  
violent_crime_2018

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
502,I192003189,423,Aggravated Assault,ASSAULT - AGGRAVATED,D4,903,NaN,2018-12-30 18:30:00,2018,12,Sunday,18,Part One,TROTTER CT,42.335968,-71.081299,"(42.33596847, -71.08129856)"
563,I192002037,423,Aggravated Assault,ASSAULT - AGGRAVATED,A1,,NaN,2018-12-11 12:30:00,2018,12,Tuesday,12,Part One,NaN,42.355475,-71.060518,"(42.35547514, -71.06051814)"
757,I182105265,423,Aggravated Assault,ASSAULT - AGGRAVATED,C11,397,NaN,2018-12-31 23:13:00,2018,12,Monday,23,Part One,LITHGOW ST,42.290372,-71.068455,"(42.29037227, -71.06845477)"
798,I182105210,423,Aggravated Assault,ASSAULT - AGGRAVATED,C11,382,NaN,2018-12-31 19:20:00,2018,12,Monday,19,Part One,GALLIVAN BLVD,42.282624,-71.055330,"(42.28262406, -71.05532964)"
955,I182105034,423,Aggravated Assault,ASSAULT - AGGRAVATED,C11,352,NaN,2018-12-31 00:55:00,2018,12,Monday,0,Part One,ADAMS ST,42.302039,-71.060091,"(42.30203902, -71.06009072)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98174,I182000616,423,Aggravated Assault,ASSAULT - AGGRAVATED,B2,901,NaN,2018-01-03 11:53:05,2018,1,Wednesday,11,Part One,PARKER ST,42.332268,-71.096748,"(42.33226842, -71.09674843)"
98378,I182000354,423,Aggravated Assault,ASSAULT - AGGRAVATED,B3,908,NaN,2018-01-02 12:36:00,2018,1,Tuesday,12,Part One,FRANKLIN HILL AVE,42.294910,-71.090192,"(42.29490954, -71.09019249)"
98489,I182000217,423,Aggravated Assault,ASSAULT - AGGRAVATED,E13,304,NaN,2018-01-01 18:25:00,2018,1,Monday,18,Part One,COLUMBUS AVE,42.317715,-71.098230,"(42.31771534, -71.09823049)"
98701,I172075311,423,Aggravated Assault,ASSAULT - AGGRAVATED,D14,783,NaN,2018-10-01 11:09:00,2018,10,Monday,11,Part One,COMMONWEALTH AVE,42.348886,-71.140074,"(42.34888559, -71.14007361)"
98764,I172034897,423,Aggravated Assault,ASSAULT - AGGRAVATED,A1,105,NaN,2018-03-06 13:30:00,2018,3,Tuesday,13,Part One,WASHINGTON ST,42.355459,-71.060524,"(42.35545896, -71.06052398)"

In [62]:
violent_crime_2017= crime_2017.loc[(crime_2017['OFFENSE_DESCRIPTION'] == 'MURDER, NON-NEGLIGENT MANSLAUGHTER') |
                             (crime_2017['OFFENSE_DESCRIPTION'] == 'ROBBERY')|
                             (crime_2017['OFFENSE_DESCRIPTION'] ==  'ASSAULT - AGGRAVATED')]
                             
                                                  
violent_crime_2017

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
276,I182027604,423,Aggravated Assault,ASSAULT - AGGRAVATED,E18,534,NaN,2017-10-09 02:40:00,2017,10,Monday,2,Part One,SOLARIS RD,42.243807,-71.143743,"(42.24380669, -71.14374305)"
330,I182021436,423,Aggravated Assault,ASSAULT - AGGRAVATED,E5,685,NaN,2017-09-03 22:38:00,2017,9,Sunday,22,Part One,MENDELSSOHN ST,42.278298,-71.138591,"(42.27829843, -71.13859143)"
597,I182003042,423,Aggravated Assault,ASSAULT - AGGRAVATED,E13,635,NaN,2017-10-03 14:00:00,2017,10,Tuesday,14,Part One,CENTRE ST,42.318172,-71.112578,"(42.31817181, -71.11257832)"
805,I182000008,423,Aggravated Assault,ASSAULT - AGGRAVATED,A1,,NaN,2017-12-31 00:00:00,2017,12,Sunday,0,Part One,SCHOOL ST,NaN,NaN,"(0.00000000, 0.00000000)"
864,I172107648,423,Aggravated Assault,ASSAULT - AGGRAVATED,B2,326,NaN,2017-12-31 18:34:00,2017,12,Sunday,18,Part One,FAYSTON ST,42.313414,-71.077896,"(42.31341383, -71.07789593)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101067,I172000103,423,Aggravated Assault,ASSAULT - AGGRAVATED,B3,468,NaN,2017-01-01 07:07:00,2017,1,Sunday,7,Part One,WALK HILL ST,42.277915,-71.094529,"(42.27791465, -71.09452937)"
101176,I162089079,423,Aggravated Assault,ASSAULT - AGGRAVATED,B2,281,NaN,2017-12-14 13:00:00,2017,12,Thursday,13,Part One,WARREN AVE,42.344539,-71.073588,"(42.34453911, -71.07358770)"
101182,I162088861,423,Aggravated Assault,ASSAULT - AGGRAVATED,D4,618,NaN,2017-09-24 18:00:00,2017,9,Sunday,18,Part One,BOYLSTON ST,42.345532,-71.094371,"(42.34553223, -71.09437093)"
101187,I162087964,423,Aggravated Assault,ASSAULT - AGGRAVATED,D4,627,NaN,2017-05-16 09:00:00,2017,5,Tuesday,9,Part One,PETERBOROUGH ST,42.343394,-71.098493,"(42.34339388, -71.09849282)"
101211,I162073342,423,Aggravated Assault,ASSAULT - AGGRAVATED,B2,184,Y,2017-02-03 00:00:00,2017,2,Friday,0,Part One,WASHINGTON ST,42.328663,-71.085634,"(42.32866284, -71.08563401)"